# Generated by Django 4.1.3 on 2022-12-10 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver_delete',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender_delete',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.CreateModel(
            name='MessageManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_delete', models.BooleanField(default=False)),
                ('readMessages', models.ManyToManyField(related_name='read_messages', to=settings.AUTH_USER_MODEL)),
                ('receivers_delete', models.ManyToManyField(related_name='receivers_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='manager',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='manager', to='message.messagemanager'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
