# Generated by Django 4.1.3 on 2022-12-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_remove_message_read_remove_message_receiver_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='manager',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='message.messagemanager'),
        ),
    ]
