# Generated by Django 4.1.3 on 2022-12-11 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemanager',
            name='sender_delete',
        ),
    ]
